spring.application.name=automata-core

spring.datasource.url=jdbc:postgresql://localhost:5432/automata-db
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.jpa.hibernate.ddl-auto=update

server.port = 8081

automata.connector.github.clientId=1234
automata.connector.github.redirectURI=uri/redirect
automata.connector.github.scope=helloFoxJatin
automata.connector.github.githubAuthURL=https://github.com/apps/automata-core/installations/new?



